import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfService {
  static Future<void> generateAndShareReport(
    Map<String, dynamic> report,
  ) async {
    final pdf = pw.Document();

    final user = report["user"];
    final latestScan = report["latest_scan"];
    final latestLog = report["latest_log"];

    final observations = latestScan?["observations"] ?? [];
    final recommendations =
        latestScan?["recommendations"] ?? report["recommendations"] ?? [];

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          pw.Text(
            "Oral Health AI Recovery Report",
            style: pw.TextStyle(fontSize: 26, fontWeight: pw.FontWeight.bold),
          ),

          pw.SizedBox(height: 8),

          pw.Text(
            "AI-assisted smoker's palate recovery summary based on latest scan, progress history, and daily logs.",
            style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
          ),

          pw.Divider(),

          sectionTitle("Patient Details"),

          infoRow("Name", user?["full_name"] ?? "User"),
          infoRow("Email", user?["email"] ?? "N/A"),

          pw.SizedBox(height: 18),

          sectionTitle("Recovery Summary"),

          infoRow("Risk Level", report["risk_level"] ?? "Unknown"),
          infoRow("Total Scans", "${report["total_scans"] ?? 0}"),
          infoRow("Total Daily Logs", "${report["total_logs"] ?? 0}"),

          infoRow(
            "Healing Score",
            latestScan?["healing_score"] == null
                ? "N/A"
                : "${latestScan["healing_score"]}/100",
          ),

          infoRow("Progress Status", latestScan?["progress_status"] ?? "N/A"),

          pw.SizedBox(height: 12),

          if (latestScan?["summary"] != null)
            noteBox("AI Summary", latestScan["summary"].toString()),

          pw.SizedBox(height: 18),

          sectionTitle("Latest Scan Result"),

          infoRow("Condition", latestScan?["condition"] ?? "No scan available"),

          infoRow(
            "AI Confidence",
            latestScan?["confidence"] == null
                ? "N/A"
                : "${latestScan["confidence"]}%",
          ),

          infoRow("Severity", latestScan?["severity"] ?? "N/A"),

          pw.SizedBox(height: 18),

          sectionTitle("Visual Observations"),

          if (observations.isEmpty)
            pw.Text(
              "No visual observations available.",
              style: const pw.TextStyle(fontSize: 12),
            )
          else
            ...observations.map<pw.Widget>((item) {
              return bullet(item.toString());
            }).toList(),

          pw.SizedBox(height: 18),

          sectionTitle("Latest Daily Log"),

          infoRow(
            "Pain Level",
            latestLog?["pain_level"] == null
                ? "No log available"
                : "${latestLog["pain_level"]}/10",
          ),

          infoRow(
            "Dryness Level",
            latestLog?["dryness_level"] == null
                ? "No log available"
                : "${latestLog["dryness_level"]}/10",
          ),

          infoRow(
            "Smoking Count",
            latestLog?["smoking_count"] == null
                ? "N/A"
                : "${latestLog["smoking_count"]}",
          ),

          infoRow(
            "Water Intake",
            latestLog?["water_intake"] == null
                ? "N/A"
                : "${latestLog["water_intake"]}",
          ),

          if (latestLog?["notes"] != null) ...[
            pw.SizedBox(height: 8),
            noteBox("Patient Notes", latestLog["notes"].toString()),
          ],

          pw.SizedBox(height: 18),

          sectionTitle("Recommendations"),

          if (recommendations.isEmpty)
            pw.Text(
              "No recommendations available.",
              style: const pw.TextStyle(fontSize: 12),
            )
          else
            ...recommendations.map<pw.Widget>((item) {
              return bullet(item.toString());
            }).toList(),

          pw.SizedBox(height: 25),

          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey200,
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Text(
              "Disclaimer: This report is generated by an AI-assisted visual wellness system. It is not a medical diagnosis and must not replace professional dental evaluation. Please consult a qualified dentist or healthcare professional for clinical decisions.",
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey800),
            ),
          ),
        ],
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: "oral_health_recovery_report.pdf",
    );
  }

  static pw.Widget sectionTitle(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 8),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize: 16,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.teal,
        ),
      ),
    );
  }

  static pw.Widget infoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 6),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            child: pw.Text(
              label,
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value, style: const pw.TextStyle(fontSize: 12)),
          ),
        ],
      ),
    );
  }

  static pw.Widget bullet(String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 6),
      child: pw.Text("• $value", style: const pw.TextStyle(fontSize: 12)),
    );
  }

  static pw.Widget noteBox(String title, String text) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.teal50,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.teal,
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(text, style: const pw.TextStyle(fontSize: 12)),
        ],
      ),
    );
  }
}
